# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vYRfZnOIqC8J2fOFOZpG8PG0S8yNoZ9x
"""

MyGraph = {
    'S' : {'A':3,'B':2},
    'A' : {'C':4,'D':1},
    'C' : {},
    'D' : {},
    'B' : {'E':3,'F':1},
    'E' : {'H':5},
    'H' : {},
    'F' : {'I':2,'G':3},
    'I' : {},
    'G' : {}
}
HeuristicValues = {
    'A':12,
    'B':4,
    'C':7,
    'D':3,
    'E':8,
    'F':2,
    'H':4,
    'I':9,
    'S':13,
    'G':0
}
StartNode='S'
GoalNode='G'

def G_BFS():
    Path=[StartNode]
    Cost=0
    Queue, Visited = [Cost,StartNode],[]
    while Queue:
        minHeuristicIndex=0
        i=0
        while i<len(Queue):
            if HeuristicValues[Queue[minHeuristicIndex+1][len(Queue[minHeuristicIndex+1])-1]] > HeuristicValues[Queue[i+1][len(Queue[i+1])-1]]:
                minHeuristicIndex=i
            i=i+2

        Cost=Queue.pop(minHeuristicIndex)
        Path=Queue.pop(minHeuristicIndex)
        Last=Path[len(Path)-1]

        if Last==GoalNode:
            Path.append("Total Cost: "+str(Cost))
            return Path

        if Last not in Visited:
            Visited.append(Last)

            for i in MyGraph[Last].keys():
                NewPath=list(Path)
                NewPath.append(i)
                Queue.append(Cost+MyGraph[Last][i])
                Queue.append(NewPath)


print(G_BFS())



